### PR TITLE
Updating the licensing model to common open source standards

### PR DESCRIPTION
**Pull request by mikaturunen**
Changed the LGPL to MIT purely based on the fact that LGPL is a bit too restrictive for certain use cases and we should be using a proper licensing model anyway.

Good work with the lib!

### CODE REVIEW

**Comment by keskival** [comment]
This would be excellent. Thumbs up!

**Comment by jjaas** [comment]
Very good! +1

**Comment by jfstephe** [comment]
Hi - can this be merged?

**Comment by cscott** [comment]
Um, who are you and why are you changing the license?

There are three people who need to agree to any license change, and they are listed in the README:
```
 Copyright &copy; 2013 C. Scott Ananian
 Copyright &copy; 2012 Eli Skeggs
 Copyright &copy; 2011 Kevin Kwok
```
You don't appear to be any of those three people.

**Pull request closed without merging**
